In [10]:
a = [1,3,5,7,9] #list
b = [2,4,6,8,10]
#位置 相乘 等不同方法

ary = []
for i in range(0,len(a)):
    ary.append(a[i]*b[i])
print(ary)

#一行文
print( [a[i]*b[i] for i in range(0,len(a)) ] )

#zip 相黏
c =[i*j for i,j in zip(a,b)]
print(c)

[2, 12, 30, 56, 90]
[2, 12, 30, 56, 90]
[2, 12, 30, 56, 90]


In [20]:
#numpy
import numpy as np
na =np.array(a)
nb =np.array(b)
print(na * nb)
print(na + nb)


[ 2 12 30 56 90]
[ 3  7 11 15 19]


In [23]:
na = np.array([1,2,3,4,5])
na[na>3]

array([4, 5])

# Numpy 2d array

In [29]:
na = np.array([[1,3,5,7,9],[2,4,6,8,10]])
na

print(na[0,0])
print(na[0,:])
print(na[:,0])
print(na.T)

1
[1 3 5 7 9]
[1 2]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [32]:
na = np.array([['frank','M',29],['tom','M',35],['lisa','F',20]])
na
#字串最大! 

array([['frank', 'M', '29'],
       ['tom', 'M', '35'],
       ['lisa', 'F', '20']], 
      dtype='<U5')

# Pandas

In [45]:
import pandas as pd
df = pd.DataFrame([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
df

0  1   2
0  frank  M  29
1   mary  F  23
2    tom  M  35
3    ted  M  33
4   jean  F  21
5   lisa  F  20

In [43]:
print(df.columns)
df.columns = ['name','gender','age']
df

Index(['name', 'gender', 'age'], dtype='object')


name gender  age
0  frank      M   29
1    tom      M   35
2    ted      M   33
3   lisa      F   20

# 在104 的爬蟲套用zip

In [46]:
import requests
res = requests.get('https://www.104.com.tw/jobbank/custjob/index.php?r=cust&j=623e466f383a426b34363e673c423a1d02d2d2d70463a4e2644j50')
res.encoding = 'utf-8'
#print(res.encoding)


from bs4 import BeautifulSoup
soup = BeautifulSoup(res.text, 'html.parser')
tag = soup.select('dt')
description = soup.select('dd')
for t, d in zip(tag, description):
    print(t.text,d.text.strip())

產業類別： 電腦軟體服務業
產業描述： 資訊軟體
員　　工： 10人
資 本 額： 200萬元
聯 絡 人： 丘先生
公司地址： 台北市中山區南京東路二段地圖
電　　話： 暫不提供
傳　　真： 暫不提供
公司網址： http://www.largitdata.com
相關連結： 更多





商業司登記
Google查公司名稱
求職服務專線 02-2912-6104 轉2
廠商求才專線 


# Pandas Series(序列)

In [49]:
s = pd.Series([21000,18900,18000])
s

0    21000
1    18900
2    18000
dtype: int64

In [53]:
s = pd.Series({'Iphone':21000,'Edge S7':18900,'HTC M1':18000})
s

Edge S7    18900
HTC M1     18000
Iphone     21000
dtype: int64

In [54]:
dic = {}
dic = 

In [68]:
#篩選數值

print(s)
print(s[2])
print('--------------')
print(s[1:3])
print('---------------')
#根據價格!
print([s<20000])
print('----------')
s['Iphone']


Edge S7    18900
HTC M1     18000
Iphone     21000
dtype: int64
21000
--------------
HTC M1    18000
Iphone    21000
dtype: int64
---------------
[Edge S7     True
HTC M1      True
Iphone     False
dtype: bool]
----------


21000

In [84]:
#修改

print(s['Iphone'])
s['Iphone'] = s['Ipone'] = 20000
print(s['Iphone'])
print('---------')
s[s<20000] = s[s<20000] * 0.8
s



20000.0
20000.0
---------


Edge S7     6193.152
HTC M1      5898.240
Iphone     20000.000
Ipone      20000.000
dtype: float64

In [88]:
print('Iphone') in s

Iphone


False

# 數學計算

In [89]:
import numpy as np
np.sqrt(s)

Edge S7     78.696582
HTC M1      76.800000
Iphone     141.421356
Ipone      141.421356
dtype: float64

In [91]:
s.describe()   #敘述性統計

count        4.000000
mean     13022.848000
std       8057.420734
min       5898.240000
25%       6119.424000
50%      13096.576000
75%      20000.000000
max      20000.000000
dtype: float64

In [93]:
s[['mi','HTC M1']]
#Nan= not a number   =  null

mi            NaN
HTC M1    5898.24
dtype: float64

In [98]:
s2 = s[['mi','HTC M1']]+s[['mi','HTC M1']]
s2

mi             NaN
HTC M1    11796.48
dtype: float64

In [103]:
#檢查是否有空值

#檢查非空值
print(s2.notnull())

#檢查空值
s2.isnull()

mi        False
HTC M1     True
dtype: bool


mi         True
HTC M1    False
dtype: bool

In [104]:
#拉出資料

In [106]:
#拉出非空值資料
s2[s2.notnull()]

HTC M1    11796.48
dtype: float64

# Pandas DataFrame

In [108]:
import pandas as pd
#使用字典方式建立較為推薦
df = pd.DataFrame([{'name':'frank', 'gender':'M', 'age':29}, \
                   {'name':'mary',  'gender':'F', 'age':23}, \
                   {'name':'tom',   'gender':'M', 'age':35}, \
                   {'name':'ted',   'gender':'M', 'age':33}, \
                   {'name':'jean',  'gender':'F', 'age':21}, \
                   {'name':'lisa',  'gender':'F', 'age':20}])
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [116]:
#自動補欄位
df = pd.DataFrame([{'name':'frank', 'gender':'M', 'age':29}, \
                   {'name':'mary',  'gender':'F', 'age':23,'marriage':'yes'}, \
                   {'name':'tom',   'gender':'M', 'age':35}])
df

age gender marriage   name
0   29      M      NaN  frank
1   23      F      yes   mary
2   35      M      NaN    tom

# 整理三大法人交易資料

In [141]:
import requests
res = requests.get('http://www.twse.com.tw/fund/BFI82U?response=json&dayDate=&weekDate=&monthDate=&type=day&_=1503112639075')
res.json()
res.json()['data']
df = pd.DataFrame(res.json()['data'])
#df.columns=['類別','數值','數值','數值']
df



0               1               2               3
0  自營商(自行買賣)   1,025,069,400     850,792,577     174,276,823
1    自營商(避險)   4,591,078,711   4,949,618,576    -358,539,865
2         投信     703,309,860     869,642,577    -166,332,717
3      外資及陸資  18,946,611,191  23,751,447,432  -4,804,836,241
4         合計  25,266,069,162  30,421,501,162  -5,155,432,000

In [137]:
df.head()

類別              數值              數值              數值
0  自營商(自行買賣)   1,025,069,400     850,792,577     174,276,823
1    自營商(避險)   4,591,078,711   4,949,618,576    -358,539,865
2         投信     703,309,860     869,642,577    -166,332,717
3      外資及陸資  18,946,611,191  23,751,447,432  -4,804,836,241
4         合計  25,266,069,162  30,421,501,162  -5,155,432,000

In [143]:
df.describe()

0            1            2             3
count       5            5            5             5
unique      5            5            5             5
top     外資及陸資  703,309,860  869,642,577  -166,332,717
freq        1            1            1             1

In [147]:
df.ix[1:4]
#ix 標籤索引

0               1               2               3
1  自營商(避險)   4,591,078,711   4,949,618,576    -358,539,865
2       投信     703,309,860     869,642,577    -166,332,717
3    外資及陸資  18,946,611,191  23,751,447,432  -4,804,836,241
4       合計  25,266,069,162  30,421,501,162  -5,155,432,000

In [150]:
df = pd.DataFrame([{'name':'frank', 'gender':'M', 'age':29}, \
                   {'name':'mary',  'gender':'F', 'age':23}, \
                   {'name':'tom',   'gender':'M', 'age':35}, \
                   {'name':'ted',   'gender':'M', 'age':33}, \
                   {'name':'jean',  'gender':'F', 'age':21}, \
                   {'name':'lisa',  'gender':'F', 'age':20}])
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

# 數據轉換

# 檔案下載 

In [155]:
import requests
res = requests.get('https://raw.githubusercontent.com/ywchiu/tibamepy/master/data/rent_591_sample.csv')
with open('rent_591_sample.csv','wb') as f:    #W=寫 B=任何方式
    f.write(res.content)


In [158]:
%ls

 磁碟區 C 中的磁碟是 OS
 磁碟區序號:  8643-363E

 C:\Users\USER 的目錄

2017/08/19  下午 01:53    <DIR>          .
2017/08/19  下午 01:53    <DIR>          ..
2017/08/12  下午 01:13    <DIR>          .anaconda
2017/08/12  下午 05:41    <DIR>          .conda
2017/08/12  下午 01:13                43 .condarc
2017/08/19  上午 09:41    <DIR>          .ipynb_checkpoints
2017/08/12  上午 10:55    <DIR>          .ipython
2017/08/12  下午 04:10    <DIR>          .jupyter
2017/08/19  上午 10:14    <DIR>          .matplotlib
2016/07/14  下午 06:07    <DIR>          .oracle_jre_usage
2017/08/12  下午 02:25    <DIR>          .spyder-py3
2017/08/13  上午 11:39            41,954 20170812.ipynb
2017/08/13  下午 05:37           339,026 20170813.ipynb
2017/08/19  下午 01:53            34,660 20170819.ipynb
2017/08/13  上午 11:13               468 2330.json
2017/08/12  下午 01:14    <DIR>          AnacondaProjects
2017/08/13  上午 09:32             2,395 cnn.txt
2015/02/12  下午 01:12    <DIR>          Contacts
2017/08/13  上午 11:39    <DIR>          Desk

In [174]:
import pandas
df = pandas.read_csv('rent_591_sample.csv',encoding='utf-8',index_col=0)
df.info()
df.head(3)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 70315 entries, 0 to 70314
Data columns (total 11 columns):
detail_url       70315 non-null object
search_date      70315 non-null object
title            70315 non-null object
address          70315 non-null object
floor_info       69686 non-null object
price            70315 non-null object
layout           22630 non-null object
building_area    70315 non-null float64
building_use     65330 non-null object
latitude         70315 non-null float64
longitude        70315 non-null float64
dtypes: float64(3), object(8)
memory usage: 6.4+ MB


detail_url search_date  \
0  https://rent.591.com.tw/rent-detail-1050934.html  2017-05-14   
1  https://rent.591.com.tw/rent-detail-1008046.html  2017-05-14   
2  https://rent.591.com.tw/rent-detail-1586266.html  2017-05-12   

                 title      address floor_info      price layout  \
0  套房出租-近東方學院(六~八月可入住)    高雄市湖內區民生街      3F/3F   4,500元/月    NaN   
1      好房子【聰明的你、妳快來租吧】    新北市蘆洲區長安街      4F/5F   7,500元/月    NaN   
2   陽台大套房(獨立洗衣機)近頂溪捷運站  新北市永和區中山路一段     8F/12F  11,000元/月    NaN   

   building_area building_use   latitude   longitude  
0            6.0     透天厝/獨立套房  22.878436  120.250810  
1           10.0     透天厝/獨立套房  25.081558  121.461868  
2            8.0    電梯大樓/分租套房  25.010293  121.511328

In [176]:
df.columns

Index(['detail_url', 'search_date', 'title', 'address', 'floor_info', 'price',
       'layout', 'building_area', 'building_use', 'latitude', 'longitude'],
      dtype='object')

In [188]:
df['building_area'] /0.3025

import numpy as np
np.sqrt(df['building_area'])
df['address'] + '-' +df['price']

#新價格存入Dataframe
df['square_feet']  = df['building_area'] /0.3025
df.head(3)

detail_url search_date  \
0  https://rent.591.com.tw/rent-detail-1050934.html  2017-05-14   
1  https://rent.591.com.tw/rent-detail-1008046.html  2017-05-14   
2  https://rent.591.com.tw/rent-detail-1586266.html  2017-05-12   

                 title      address floor_info      price layout  \
0  套房出租-近東方學院(六~八月可入住)    高雄市湖內區民生街      3F/3F   4,500元/月    NaN   
1      好房子【聰明的你、妳快來租吧】    新北市蘆洲區長安街      4F/5F   7,500元/月    NaN   
2   陽台大套房(獨立洗衣機)近頂溪捷運站  新北市永和區中山路一段     8F/12F  11,000元/月    NaN   

   building_area building_use   latitude   longitude  square_feet  
0            6.0     透天厝/獨立套房  22.878436  120.250810    19.834711  
1           10.0     透天厝/獨立套房  25.081558  121.461868    33.057851  
2            8.0    電梯大樓/分租套房  25.010293  121.511328    26.446281

In [192]:
def normalizePrice(price):
    return int(''.join(price.strip('元/月').split(',')))
normalizePrice('4,500元/月')


4500

In [194]:
df['price'].map(lambda price: int(''.join(price.strip('元/月').split(',')))).head()

0     4500
1     7500
2    11000
3     5000
4     5000
Name: price, dtype: int64

In [196]:
df.applymap(lambda e: '-' if pandas.isnull(e) else e).head(3)

detail_url search_date  \
0  https://rent.591.com.tw/rent-detail-1050934.html  2017-05-14   
1  https://rent.591.com.tw/rent-detail-1008046.html  2017-05-14   
2  https://rent.591.com.tw/rent-detail-1586266.html  2017-05-12   

                 title      address floor_info      price layout  \
0  套房出租-近東方學院(六~八月可入住)    高雄市湖內區民生街      3F/3F   4,500元/月      -   
1      好房子【聰明的你、妳快來租吧】    新北市蘆洲區長安街      4F/5F   7,500元/月      -   
2   陽台大套房(獨立洗衣機)近頂溪捷運站  新北市永和區中山路一段     8F/12F  11,000元/月      -   

   building_area building_use   latitude   longitude  square_feet  
0            6.0     透天厝/獨立套房  22.878436  120.250810    19.834711  
1           10.0     透天厝/獨立套房  25.081558  121.461868    33.057851  
2            8.0    電梯大樓/分租套房  25.010293  121.511328    26.446281

In [237]:
df.fillna('^_^').head()

detail_url search_date  \
0  https://rent.591.com.tw/rent-detail-1050934.html  2017-05-14   
1  https://rent.591.com.tw/rent-detail-1008046.html  2017-05-14   
2  https://rent.591.com.tw/rent-detail-1586266.html  2017-05-12   
3  https://rent.591.com.tw/rent-detail-1699948.html  2017-05-13   
4  https://rent.591.com.tw/rent-detail-1404725.html  2017-05-12   

                 title      address floor_info      price layout  \
0  套房出租-近東方學院(六~八月可入住)    高雄市湖內區民生街      3F/3F   4,500元/月    ^_^   
1      好房子【聰明的你、妳快來租吧】    新北市蘆洲區長安街      4F/5F   7,500元/月    ^_^   
2   陽台大套房(獨立洗衣機)近頂溪捷運站  新北市永和區中山路一段     8F/12F  11,000元/月    ^_^   
3          火車站附近~~優質套房    屏東縣潮州鎮六合路      3F/3F   5,000元/月    ^_^   
4          觀音四維路優質陽台套房    桃園市觀音區四維路      4F/5F   5,000元/月    ^_^   

   building_area building_use   latitude   longitude  square_feet  
0            6.0     透天厝/獨立套房  22.878436  120.250810    19.834711  
1           10.0     透天厝/獨立套房  25.081558  121.461868    33.057851  
2            8.0    電梯大樓/分租套房  25.010293  121.511328    26.446281  
3            8.0     透天厝/獨立套房  22.551346  120.538032    26.446281  
4            7.0     透天厝/分租套房  25.043652  121.141518    23.140496


# 處理時間格式

# regular expression

In [211]:
import re
a = '5'
#[] 裡面元素用或來比對

#  -代表連續
print(re.match('[0-9]',a))

# /d 代表0-9

print(re.match('\d',a))
      

<_sre.SRE_Match object; span=(0, 1), match='5'>
<_sre.SRE_Match object; span=(0, 1), match='5'>


# 比對英文字母

In [212]:
s = 'g'
print(re.match('[a-z]',s))

s2 = 'G'
print(re.match('[a-zA-Z]',s2))  #比對大小寫


<_sre.SRE_Match object; span=(0, 1), match='g'>
<_sre.SRE_Match object; span=(0, 1), match='G'>


# 同時比對英文數字

In [221]:
s = '5'
re.match('[a-zA-Z0-9]', s)

# \w == [a-zA-Z0-9]
re.match('\w', s)

<_sre.SRE_Match object; span=(0, 1), match='5'>

# 特殊字元

In [ ]:
# .   == 任意字元
A = '$'
re.match('.',a)

# 比對車牌

In [229]:
s =  '9988'

#{} 裡面的數字代表要比對到的數量
re.match('\d{4}',s)

#{s,e}  代表至少有多少符號 e代表至多有多少符號
print(re.match('\d{3,5}',s))


#{s, } 至少比對到s個數量符號
print(re.match('\d{3,}', s))

# * == {0, } 
re.match('\d*', s)

# {1, } 至少比對到 1 數量以上符號
re.match('\d{1,}', s)

# + == {1, } 
re.match('\d+', s)



<_sre.SRE_Match object; span=(0, 4), match='9988'>
<_sre.SRE_Match object; span=(0, 4), match='9988'>


<_sre.SRE_Match object; span=(0, 4), match='9988'>

# 比對電話號碼

In [233]:
p = '0912345678'
re.match('\d{10}', p)

p2 = '1234567890'
re.match('\d{10}', p2)df2 = 
df.pivot_table(index='search_date', columns='building_use', values='price', aggfunc='mean')
df2.head()

re.match('09\d{8}', p )

<_sre.SRE_Match object; span=(0, 10), match='0912345678'>

In [234]:
phones = ['0912345678', '0912-345678', '0912-345-678']
for p in phones:
    #print(re.match('09\d{8}' , p))
    #print(re.match('09\d{2}-{0,1}\d{3}-{0,1}\d{3}' , p))
    
    # {0,1} == ?
    print(re.match('09\d{2}-?\d{3}-?\d{3}' , p))

<_sre.SRE_Match object; span=(0, 10), match='0912345678'>
<_sre.SRE_Match object; span=(0, 11), match='0912-345678'>
<_sre.SRE_Match object; span=(0, 12), match='0912-345-678'>


In [239]:
phones = ['0912345678', '0912-345678', '0912-345-678', '0912930183109830130913']
for p in phones:
    # ^ 強制比對開頭, $ 強制結尾
    print(re.match('^09\d{2}-?\d{3}-?\d{3}$' , p))

<_sre.SRE_Match object; span=(0, 10), match='0912345678'>
<_sre.SRE_Match object; span=(0, 11), match='0912-345678'>
<_sre.SRE_Match object; span=(0, 12), match='0912-345-678'>
None


# io

In [243]:

import pandas
m_cols = ['Time','Action','User','Product', 'Quantity','Price']
df = pandas.read_csv('https://raw.githubusercontent.com/ywchiu/tibamepy/master/data/purchase_order.tab', \
                     sep = '\t', header = None,  parse_dates={'Dates': [0]}, names=m_cols)
df.head()

Dates Action          User         Product  Quantity   Price
0 2015-07-01 00:00:01  order    U312622727     P0006944501         1  1069.0
1 2015-07-01 00:00:03  order    U239012343     P0006018073         1  1680.0
2 2015-07-01 00:00:19  order  U10007697373     P0002267974         1   285.0
3 2015-07-01 00:01:10  order    U296328517     P0016144236         1   550.0
4 2015-07-01 00:01:36  order    U300884570  P0014516980122         1   249.0

# 抓取台銀匯率

In [257]:
import pandas
dfs = pandas.read_html('http://rate.bot.com.tw/xrt/quote/l6m/USD')

In [259]:
dfs[0]

掛牌日期                幣別    現金匯率 Unnamed: 4_level_0  \
           本行買入      本行賣出    本行買入    本行賣出 Unnamed: 4_level_1   
0    2017/08/18  美金 (USD)  29.970  30.512             30.270   
1    2017/08/17  美金 (USD)  29.955  30.497             30.255   
2    2017/08/16  美金 (USD)  30.000  30.542             30.300   
3    2017/08/15  美金 (USD)  29.935  30.477             30.235   
4    2017/08/14  美金 (USD)  29.950  30.492             30.250   
5    2017/08/11  美金 (USD)  29.985  30.527             30.285   
6    2017/08/10  美金 (USD)  29.950  30.492             30.250   
7    2017/08/09  美金 (USD)  29.865  30.407             30.165   
8    2017/08/08  美金 (USD)  29.840  30.382             30.140   
9    2017/08/07  美金 (USD)  29.875  30.417             30.175   
10   2017/08/04  美金 (USD)  29.835  30.377             30.135   
11   2017/08/03  美金 (USD)  29.850  30.392             30.150   
12   2017/08/02  美金 (USD)  29.870  30.412             30.170   
13   2017/08/01  美金 (USD)  29.880  30.422             30.180   
14   2017/07/31  美金 (USD)  29.845  30.387             30.145   
15   2017/07/28  美金 (USD)  29.915  30.457             30.215   
16   2017/07/27  美金 (USD)  29.880  30.422             30.180   
17   2017/07/26  美金 (USD)  30.030  30.572             30.330   
18   2017/07/25  美金 (USD)  29.985  30.527             30.285   
19   2017/07/24  美金 (USD)  29.990  30.532             30.290   
20   2017/07/21  美金 (USD)  30.090  30.632             30.390   
21   2017/07/20  美金 (USD)  30.100  30.642             30.400   
22   2017/07/19  美金 (USD)  30.035  30.577             30.335   
23   2017/07/18  美金 (USD)  30.010  30.552             30.310   
24   2017/07/17  美金 (USD)  30.065  30.607             30.365   
25   2017/07/14  美金 (USD)  30.050  30.592             30.350   
26   2017/07/13  美金 (USD)  30.010  30.552             30.310   
27   2017/07/12  美金 (USD)  30.130  30.672             30.430   
28   2017/07/11  美金 (USD)  30.225  30.767             30.525   
29   2017/07/10  美金 (USD)  30.235  30.777             30.535   
..          ...       ...     ...     ...                ...   
94   2017/04/06  美金 (USD)  30.205  30.747             30.505   
95   2017/04/05  美金 (USD)  30.035  30.577             30.335   
96   2017/03/31  美金 (USD)  29.980  30.522             30.280   
97   2017/03/30  美金 (USD)  29.955  30.497             30.255   
98   2017/03/29  美金 (USD)  29.920  30.462             30.220   
99   2017/03/28  美金 (USD)  29.815  30.357             30.115   
100  2017/03/27  美金 (USD)  29.900  30.442             30.200   
101  2017/03/24  美金 (USD)  30.135  30.677             30.435   
102  2017/03/23  美金 (USD)  30.125  30.667             30.425   
103  2017/03/22  美金 (USD)  30.145  30.687             30.445   
104  2017/03/21  美金 (USD)  30.105  30.647             30.405   
105  2017/03/20  美金 (USD)  30.185  30.727             30.485   
106  2017/03/17  美金 (USD)  30.280  30.822             30.580   
107  2017/03/16  美金 (USD)  30.345  30.887             30.645   
108  2017/03/15  美金 (USD)  30.490  31.032             30.790   
109  2017/03/14  美金 (USD)  30.615  31.157             30.915   
110  2017/03/13  美金 (USD)  30.600  31.142             30.900   
111  2017/03/10  美金 (USD)  30.690  31.232             30.990   
112  2017/03/09  美金 (USD)  30.665  31.207             30.965   
113  2017/03/08  美金 (USD)  30.525  31.067             30.825   
114  2017/03/07  美金 (USD)  30.500  31.042             30.800   
115  2017/03/06  美金 (USD)  30.630  31.172             30.930   
116  2017/03/03  美金 (USD)  30.675  31.217             30.975   
117  2017/03/02  美金 (USD)  30.445  30.987             30.745   
118  2017/03/01  美金 (USD)  30.420  30.962             30.720   
119  2017/02/24  美金 (USD)  30.300  30.842             30.600   
120  2017/02/23  美金 (USD)  30.390  30.932             30.690   
121  2017/02/22  美金 (USD)  30.430  30.972             30.730   
122  2017/02/21  美金 (USD)  30.440  30.982             30.740   
123  2017/02/20  美金 (USD)  30.450  30.992  

In [261]:
df.plot(kind = 'line')